= Getting Started with the Python Client
:page-layout: tutorial
:page-product: imdg
:page-categories: Caching, Getting Started
:page-lang: python3
:page-est-time: 5-10 mins
:description: This tutorial will get you started with the Hazelcast Python client.

== What You Will Learn

{description}

== Before You Begin

* A text editor

* Hazelcast Cluster. You can use any of them below. In this tutorial, local cluster will be used.

** Local Hazelcast Cluster

** https://hazelcast.com/products/viridian/[Hazelcast Viridian] (Free account is available.)

* Python 3.6+

* Windows, Linux/UNIX or Mac OS X

== Installing Hazelcast Cluster

1. Go to https://hazelcast.com/open-source-projects/downloads/[Hazelcast Open Source Downloads] and download either the .zip or .tar distribution of Hazelcast.

2. Decompress the contents into any directory that you want to run members from.

3. Change into the directory that you decompressed the Hazelcast content and then into the bin directory.

4. To start the cluster, use either hz-start or hz-start.bat depending on your operating system. Once you run the start script, you should see the Hazelcast logs in the terminal.

== Installing and Starting with the Client

Create a new folder by

[source, bash]
mkdir hazelcast-python-client-getting-started

Navigate to that folder by

[source, bash]
cd hazelcast-python-client-getting-started

Hazelcast Python Client can be installed by pip3. Run the following command.

[source, bash]
pip3 install hazelcast-python-client

Create a file named tutorial.py

Put the following code inside of tutorial.py.

[source, python]
----
import hazelcast

client = hazelcast.HazelcastClient()

client.shutdown()
----
To run this Python script, use the following command in the terminal.

[source, bash]
python3 tutorial.py

First line imports the Hazelcast Python client.

Following line creates and starts a new Hazelcast Client. To configure the client, you can check https://hazelcast.readthedocs.io/en/stable/client.html#hazelcast.client.HazelcastClient[API documentation].

== Use Map

A Hazelcast map is a distributed key-value store, similar to Python Map structure. In the following example, we will work with map entries where the keys are session ids and the values are emails.

[source, python]
----
import hazelcast

client = hazelcast.HazelcastClient()

some_map = client.get_map("some-map").blocking()

some_map.set("12345", "example1@email.com")
some_map.set("12346", "example2@email.com")

entries = some_map.entry_set()

for key, value in entries:
    print(f"{key} -> {value}")

client.shutdown()
----


The output snippet is
[source, bash]
----
12346 -> example2@email.com
12345 -> example1@email.com
----

Since Hazelcast clients work asynchronous, our output is not in order.

Following line returns a map proxy object for the `some-map` named map.

[source, python]
some_map = client.get_map("some-map").blocking()

If there is not a map named `some-map`, it will be automatically created. All the clients connected to the same cluster will have access to same map.

You may wonder why we have used `blocking()` method over the `get_map()`. This returns a version of this proxy with only blocking (sync) method calls, which is better for getting started. For async calls, please check our https://hazelcast.readthedocs.io/en/stable/client.html#hazelcast.client.HazelcastClient[API documentation].

With these lines, client adds data to our `some-map`. The first parameter is the key of the entry, the second one is the value as mentioned above.

[source, python]
----
some_map.set("12345", "example1@email.com")
some_map.set("12346", "example2@email.com")
----

Then, we get the values with the `entry_set()` method.

Finally, `client.shutdown()` shutdowns our client.

== Add a Listener to the Map

You can add entry listener using the `add_entry_listener()` method available on map proxy object. This will allow you to listen to certain events that happen in the map across the cluster.

The first argument to `add_entry_listener()` method is `includeValue`. It is a boolean parameter, and if it is true, the entry event contains the entry value. In this example, it will be true.

The second argument to `add_entry_listener()` method is an object that is used to define listeners. In this example, we registered listeners for the `added`, `removed` and `updated` events.

[source, python]
----
import hazelcast

def entry_added(event):
    print(f"Entry added with key: {event.key}, value: {event.value}")


def entry_removed(event):
    print(f"Entry removed with key: {event.key}")


def entry_updated(event):
    print(f"Entry updated with key: {event.key}, old value: {event.old_value}, new value: {event.value}")


client = hazelcast.HazelcastClient()

some_map = client.get_map("some-map").blocking()

some_map.clear()

some_map.add_entry_listener(
    True, added_func=entry_added, removed_func=entry_removed, updated_func=entry_updated
)

some_map.set("12345", "example1@email.com")
some_map.set("12346", "example2@email.com")

email1 = some_map.get("12345")
email2 = some_map.get("12346")

print(f"Email 1: {email1}")
print(f"Email 2: {email2}")

some_map.delete("12345")
some_map.set("12346", "example1@email.com")

email1 = some_map.get("12345")
email2 = some_map.get("12346")

print(f"Email 1: {email1}")
print(f"Email 2: {email2}")

client.shutdown()
----

First, the map is cleared to fire events even if there are some entries in the map. Then, two session entries are added, and they are logged. After that, we remove one of the entries and update the other one. Then, we log the session entries again.

The output is as follows.

[source, bash]
----
Entry added with key: 12345, value: example1@email.com
Entry added with key: 12346, value: example2@email.com
Email 1: example1@email.com
Email 2: example2@email.com
Entry removed with key: 12345
Entry updated with key: 12346, old value: example2@email.com, new value: example1@email.com
Email 1: None
Email 2: example1@email.com
----
The value of the first entry becomes `None` since it is removed.

== Summary

In this tutorial, you learned how to get started with Hazelcast Python Client using a distributed map.

== See Also

There are a lot of things that you can do with Python Client. For more, such as how you can query a map with predicates and SQL, check out our https://github.com/hazelcast/hazelcast-python-client[Python Client repository].

If you have any questions, suggestions, or feedback please do not hesitate to reach out to us via https://slack.hazelcast.com/[Hazelcast Community Slack]. Also, please take a look at https://github.com/hazelcast/hazelcast-python-client/issues[the issue list] if you would like to contribute to the client.
